onlyBuiltDependencies:
  - "adhocracy4@https://codeload.github.com/liqd/adhocracy4/tar.gz/9e1229042749ec6043ffd92c7fb5a385118aea06"
  - dsgvo-video-embed
  - leaflet.markercluster
  - datepicker
  - "@parcel/watcher"
  - maplibre-gl
