# Generated by Django 4.2.22 on 2025-10-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_livequestions", "0006_ckeditor_iframes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livestream",
            options={"base_manager_name": "objects"},
        ),
    ]
