# Generated by Django 4.2.11 on 2024-12-02 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.A4_ORGANISATIONS_MODEL),
        ("a4administrative_districts", "0001_initial"),
        ("a4projects", "0047_alter_project_image_alter_project_tile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KiezradarQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name_plural": "queries",
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation",
                    models.SmallIntegerField(
                        choices=[
                            (0, "information (no participation)"),
                            (1, "consultation"),
                            (2, "cooperation"),
                            (3, "decision-making"),
                        ],
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "running"), (1, "done")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "districts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="search_profiles",
                        to="a4administrative_districts.administrativedistrict",
                    ),
                ),
                (
                    "organisations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="search_profiles",
                        to=settings.A4_ORGANISATIONS_MODEL,
                    ),
                ),
                (
                    "project_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="search_profiles",
                        to="meinberlin_kiezradar.projecttype",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_profiles",
                        to="meinberlin_kiezradar.kiezradarquery",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="search_profiles",
                        to="a4projects.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
