# Generated by Django 4.2.11 on 2024-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0002_add_participation_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchprofile",
            name="notification",
            field=models.BooleanField(default=False),
        ),
    ]
