# Generated by Django 4.2.11 on 2025-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0002_add_participation_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchprofile",
            name="plans_only",
            field=models.BooleanField(default=False),
        ),
    ]
