# Generated by Django 4.2.11 on 2025-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0003_searchprofile_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "running"), (1, "done"), (2, "future")],
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="searchprofile",
            name="status",
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="status",
            field=models.ManyToManyField(
                blank=True,
                related_name="search_profiles",
                to="meinberlin_kiezradar.projectstatus",
            ),
        ),
    ]
