# Generated by Django 4.2.16 on 2025-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0003_searchprofile_plans_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchprofile",
            name="kiezradar",
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="kiezradars",
            field=models.ManyToManyField(
                blank=True,
                related_name="search_profiles",
                to="meinberlin_kiezradar.kiezradar",
            ),
        ),
    ]
