# Generated by Django 4.2.16 on 2025-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0004_alter_kiezradar_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchprofile",
            name="kiezradar",
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="kiezradars",
            field=models.ManyToManyField(
                blank=True,
                related_name="search_profiles",
                to="meinberlin_kiezradar.kiezradar",
            ),
        ),
        migrations.AlterField(
            model_name="projectstatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "running"), (1, "future"), (2, "done")],
                verbose_name="Status",
            ),
        ),
    ]
