# Generated by Django 4.2.16 on 2025-02-19 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0004_remove_searchprofile_kiezradar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kiezradar",
            name="point",
        ),
    ]
