# Generated by Django 4.2.11 on 2025-01-07 07:59

from django.db import migrations


def populate_project_status(apps, schema_editor):
    ProjectStatus = apps.get_model("meinberlin_kiezradar", "ProjectStatus")
    ProjectStatus.objects.bulk_create(
        [
            ProjectStatus(status=0),
            ProjectStatus(status=1),
            ProjectStatus(status=2),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0004_add_project_status"),
    ]

    operations = [
        migrations.RunPython(populate_project_status),
    ]
