# Generated by Django 4.2.16 on 2025-02-19 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0005_kiezradar_remove_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiezradar",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                null=True,
                help_text="Click inside the marked area or type in an address to set the marker. A set marker can be dragged when pressed.",
                srid=4326,
                verbose_name="Where can your address be located on a map?",
            ),
        ),
    ]
