# Generated by Django 4.2.11 on 2025-01-09 15:26

from django.db import migrations, models


def add_number_to_search_profiles(apps, schema_editor):
    SearchProfile = apps.get_model("meinberlin_kiezradar", "SearchProfile")
    for sp in SearchProfile.objects.all():
        if sp.number is None:
            latest = None
            try:
                latest = (
                    SearchProfile.objects.filter(number__isnull=False)
                    .filter(user=sp.user)
                    .latest("number")
                )
            except SearchProfile.DoesNotExist:
                pass
            sp.number = latest.number + 1 if latest else 1
            sp.save()


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_kiezradar", "0006_searchprofile_number"),
    ]

    operations = [
        migrations.RunPython(add_number_to_search_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="searchprofile",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="searchprofile",
            constraint=models.UniqueConstraint(
                models.F("user"), models.F("number"), name="unique-search-profile"
            ),
        ),
    ]
