# Generated by Django 4.2.16 on 2025-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0006_kiezradar_add_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectstatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "running"), (1, "future"), (2, "done")],
                verbose_name="Status",
            ),
        ),
    ]
