# Generated by Django 4.2.11 on 2025-01-15 18:44

import adhocracy4.maps.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meinberlin_kiezradar", "0007_alter_searchprofile_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KiezRadar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                (
                    "point",
                    adhocracy4.maps.fields.PointField(
                        blank=True,
                        help_text="Click inside the marked area or type in an address to set the marker. A set marker can be dragged when pressed.",
                        verbose_name="Where can your address be located on a map?",
                    ),
                ),
                (
                    "radius",
                    models.FloatField(
                        help_text="How long should be the radius area?",
                        validators=[
                            django.core.validators.MinValueValidator(500.0),
                            django.core.validators.MaxValueValidator(3000.0),
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiezradar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="kiezradar",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_profile",
                to="meinberlin_kiezradar.kiezradar",
            ),
        ),
    ]
