# Generated by Django 4.2.26 on 2025-11-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0011_bplan_is_diplan_alter_bplan_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bplan",
            name="identifier",
        ),
    ]
