# Generated by Django 5.2.13 on 2026-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0013_retype_statement_phase_to_external"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Statement",
        ),
    ]
