# Generated by Django 5.2.13 on 2026-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0014_delete_statement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bplan",
            name="is_diplan",
        ),
    ]
