# Generated by Django 4.2.11 on 2025-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_users", "0007_add_error_message_username_used_as_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="get_newsletters",
            field=models.BooleanField(
                default=False,
                help_text="Yes, I would like to receive e-mail newsletters about the projects I am following. I can undo this at any time in my user account settings.",
                verbose_name="Newsletter",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="get_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Yes, I would like to be notified by e-mail about the start and end of participation opportunities. This applies to all projects I follow. I also receive an e-mail when someone comments on one of my contributions. I can adapt notification in my user account settings. ",
                verbose_name="Notifications",
            ),
        ),
    ]
