# Generated by Django 4.2.16 on 2025-02-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_notifications", "0003_add_notification_settings_per_user"),
        ("meinberlin_users", "0008_change_registration_helptext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="get_newsletters",
        ),
        migrations.RemoveField(
            model_name="user",
            name="get_notifications",
        ),
    ]
