# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_projects', '0001_initial'),
    ]


    database_operations = [
        migrations.AlterModelTable('ModeratorInvite', 'meinberlin_projectinvites_moderatorinvite'),
        migrations.AlterModelTable('ParticipantInvite', 'meinberlin_projectinvites_participantinvite'),
    ]

    state_operations = [
        migrations.DeleteModel('ModeratorInvite'),
        migrations.DeleteModel('ParticipantInvite'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
