# Generated by Django 4.2.10 on 2024-07-11 13:52

from django.db import migrations, models
from meinberlin.apps.projects.helpers import public_projects_raw_query

sql = public_projects_raw_query()


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_projects", "0005_topics"),
    ]

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name="PublicProjectView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PublicProject",
                "verbose_name_plural": "PublicProjects",
                "db_table": "public_project_view",
                "managed": False,
            },
        ),
    ]
