# Generated by Django 4.2.16 on 2025-02-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4projects", "0047_alter_project_image_alter_project_tile_image"),
        ("meinberlin_projects", "0005_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("unregistered_participants", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("ratings", models.PositiveIntegerField(default=0)),
                ("written_ideas", models.PositiveIntegerField(default=0)),
                ("poll_answers", models.PositiveIntegerField(default=0)),
                ("live_questions", models.PositiveIntegerField(default=0)),
                (
                    "active_participants",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="a4projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
