# Generated by Django 4.2.16 on 2025-02-03 08:44
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def create_notification_settings_per_user(apps, schema_editor):
    NotificationSettings = apps.get_model(
        "meinberlin_notifications", "NotificationSettings"
    )
    User = apps.get_model("meinberlin_users", "User")

    for user in User.objects.all():
        try:
            NotificationSettings.objects.create(
                user=user,
                email_newsletter=user.get_newsletters,
                notify_followers_phase_started=user.get_notifications,
                notify_followers_phase_over_soon=user.get_notifications,
                notify_followers_event_upcoming=user.get_notifications,
                notify_creator=user.get_notifications,
                notify_creator_on_moderator_feedback=user.get_notifications,
                notify_initiators_project_created=user.get_notifications,
                notify_moderator=user.get_notifications,
            )
        except Exception as e:
            logger.warning(
                "error migrating notification settings for user " + user + ": " + str(e)
            )


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_notifications", "0002_notificationsettings"),
    ]

    operations = [
        migrations.RunPython(
            create_notification_settings_per_user, migrations.RunPython.noop
        ),
    ]
