# Generated by Django 4.2.16 on 2025-02-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezradar", "0007_alter_projectstatus_status"),
        ("meinberlin_notifications", "0003_add_notification_settings_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="search_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="meinberlin_kiezradar.searchprofile",
            ),
        ),
    ]
