# Generated by Django 4.2.16 on 2025-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_notifications", "0004_notification_search_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="track_creator",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="track_creator_on_moderator_feedback",
            field=models.BooleanField(default=True),
        ),
    ]
