# Generated by Django 4.2.22 on 2025-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "meinberlin_notifications",
            "0005_notificationsettings_track_creator_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationsettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationSettings",
        ),
    ]
