# Generated by Django 4.2.22 on 2025-08-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("a4notifications", "0002_remove_notification_search_profile"),
        (
            "meinberlin_notifications",
            "0005_notificationsettings_track_creator_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="action",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read_at",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="email_newsletter",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="id",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_creator",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_creator_on_moderator_feedback",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_followers_event_upcoming",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_followers_phase_over_soon",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_followers_phase_started",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_initiators_project_created",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notify_moderator",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="track_creator",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="track_creator_on_moderator_feedback",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="track_followers_event_upcoming",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="track_followers_phase_over_soon",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="track_followers_phase_started",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="a4notifications.notification",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="notificationsettings_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="a4notifications.notificationsettings",
            ),
            preserve_default=False,
        ),
    ]
