# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 13:15
from __future__ import unicode_literals

import adhocracy4.ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4modules', '0004_description_maxlength_512'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceToFace',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a4modules.Item')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('text', adhocracy4.ckeditor.fields.RichTextCollapsibleUploadingField()),
            ],
            options={
                'abstract': False,
            },
            bases=('a4modules.item',),
        ),
    ]
