# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 08:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_facetoface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetoface',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
