# Generated by Django 4.2.22 on 2025-10-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("a4modules", "0008_alter_module_blueprint_type"),
        ("meinberlin_offlineevents", "0011_ckeditor_iframes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineEventSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Date")),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_settings",
                        to="a4modules.module",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
