# Generated by Django 4.2.22 on 2025-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0012_offlineeventsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineeventsettings",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
    ]
