# Generated by Django 4.2.22 on 2025-10-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0013_migrate_offlineevent_to_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offlineeventitem",
            options={"base_manager_name": "objects"},
        ),
    ]
