# Generated by Django 4.2.22 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_offlineevents', '0013_alter_offlineeventsettings_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineeventsettings',
            name='event_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Event type'),
        ),
    ]
