# Generated by Django 4.2.22 on 2025-11-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0014_alter_offlineeventitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineeventitem",
            name="name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Name"
            ),
        ),
    ]
