# Generated by Django 4.2.26 on 2025-12-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0016_fix_offlineeventitem_polymorphic_ctype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfflineEvent",
        ),
    ]
