# Generated by Django 5.2.10 on 2026-01-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0017_delete_offlineevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offlineeventitem",
            options={},
        ),
    ]
