# Generated by Django 4.2.22 on 2025-10-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "meinberlin_offlineevents",
            "0019_offlineeventitem_delete_offlineeventsettings",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="offlineeventitem",
            old_name="event_type",
            new_name="eventtype",
        ),
    ]
