# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 14:45
from __future__ import unicode_literals

from django.db import migrations
import meinberlin.apps.ckeditor_collapsible.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0003_rename_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=meinberlin.apps.ckeditor_collapsible.fields.RichTextCollapsibleField(blank=True, verbose_name='Description'),
        ),
    ]
