# Generated by Django 4.2.16 on 2025-01-30 16:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0064_ckeditor_iframes"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="geos_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                null=True,
                srid=4326,
                verbose_name="Can your plan be located on the map?",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="house_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="street_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
