# Generated by Django 4.2.17 on 2025-01-27 15:11

import json
import logging

from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_plan_point_field(apps, schema_editor):
    plan = apps.get_model("meinberlin_plans", "Plan")
    for plan in plan.objects.all():
        geojson_point = plan.point
        if not geojson_point:
            continue
        if not "geometry" in geojson_point:
            logger.warning(
                "error migrating point of plan " + plan.name + ": " + str(geojson_point)
            )
            continue
        plan.geos_point = GEOSGeometry(json.dumps(geojson_point["geometry"]))
        if "properties" in geojson_point:
            properties = geojson_point["properties"]
            if "strname" in properties:
                plan.street_name = properties["strname"]
            if "hsnr" in properties:
                plan.house_number = properties["hsnr"]
            if "plz" in properties:
                plan.zip_code = properties["plz"]
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "meinberlin_plans",
            "0065_plan_geos_point_plan_house_number_plan_street_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrate_plan_point_field, reverse_code=migrations.RunPython.noop
        ),
    ]
