# Generated by Django 4.2.16 on 2025-02-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0066_migrate_data_from_point_to_geos_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="point",
        ),
    ]
