# Generated by Django 4.2.16 on 2025-02-19 15:56

from django.db import migrations


def migrate_plan_geos_point_field(apps, schema_editor):
    plans = apps.get_model("meinberlin_plans", "Plan")
    for plan in plans.objects.all():
        plan.point = plan.geos_point
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0067_replace_point_field"),
    ]

    operations = [
        migrations.RunPython(
            migrate_plan_geos_point_field, reverse_code=migrations.RunPython.noop
        ),
    ]
