# Generated by Django 4.2.16 on 2025-02-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0069_migrate_point_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="geos_point",
        ),
    ]
