# Generated by Django 3.2.16 on 2023-01-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_budgeting", "0031_alter_proposal_moderator_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="moderator_statement",
            new_name="moderator_feedback_text",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="moderator_feedback",
            new_name="moderator_status",
        ),
    ]
