# Generated by Django 4.2.16 on 2025-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_budgeting", "0034_alter_proposal_completed_tasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived suggestions do not appear in the ideas and proposals list by default. They can be found using the corresponding filter. Rating, support and voting are no longer possible, the comment function remains.",
                verbose_name="Proposal is archived (public)",
            ),
        ),
    ]
