# Generated by Django 4.2.22 on 2025-10-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_activities", "0004_alter_activity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"base_manager_name": "objects"},
        ),
    ]
