# Generated by Django 4.2 on 2023-12-14 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_activities", "0004_alter_activity_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
