# Generated by Django 5.2.10 on 2026-01-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_activities", "0005_alter_activity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={},
        ),
    ]
