# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meinberlin.apps.cms.mixins
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('meinberlin_cms', '0018_add_imgage_cta_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Calendar',
            },
            bases=(meinberlin.apps.cms.mixins.PaginatorMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('place', models.CharField(max_length=32)),
                ('contact', models.EmailField(max_length=254)),
                ('short_description', models.CharField(help_text='Shown on the homepage.', max_length=112)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Event',
            },
            bases=('wagtailcore.page',),
        ),
    ]
