# Generated by Django 3.2.17 on 2023-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_cms", "0039_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefront",
            name="num_entries",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="storefront",
            name="num_projects",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
