# Generated by Django 3.2.20 on 2023-09-20 15:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_cms", "0041_storefrontitem_district_project_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterMenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_title", models.CharField(max_length=255)),
                (
                    "page_link",
                    wagtail.fields.StreamField(
                        [
                            (
                                "link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_text",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "link",
                                            wagtail.blocks.PageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_text",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Please enter a full url which starts with https:// or http://",
                                                max_length=500,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FooterNavigationMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterNavigationMenuItem",
            fields=[
                (
                    "footermenuitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="meinberlin_cms.footermenuitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meinberlin_cms.footernavigationmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("meinberlin_cms.footermenuitem", models.Model),
        ),
    ]
