# Generated by Django 3.2.20 on 2023-09-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        (
            "meinberlin_cms",
            "0042_footermenuitem_footernavigationmenu_footernavigationmenuitem",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="headerpages",
            name="accessibility_declaration",
            field=models.ForeignKey(
                blank=True,
                help_text="Please add a link to your accesibility decleration page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessibility_declaration_page",
                to="wagtailcore.page",
                verbose_name="Accessibility Decleration Page",
            ),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="accessibility_declaration_link_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="additional_external_info",
            field=models.URLField(
                blank=True, help_text="Add link for additional information"
            ),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="additional_external_info_link_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="feedback_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="feedback_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headerpages",
            name="feedback_phone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
