# Generated by Django 3.2.20 on 2023-09-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        (
            "meinberlin_cms",
            "0042_footermenuitem_footernavigationmenu_footernavigationmenuitem",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_name", models.CharField(blank=True, max_length=255)),
                ("feedback_email", models.EmailField(blank=True, max_length=255)),
                ("feedback_phone", models.CharField(blank=True, max_length=255)),
                (
                    "additional_external_info",
                    models.URLField(
                        blank=True, help_text="Add link to further information"
                    ),
                ),
                (
                    "additional_external_info_title",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "accessibility_declaration_title",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "accessibility_declaration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessibility_declaration_page",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
