# Generated by Django 4.2.10 on 2024-09-16 14:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0045_create_accordion_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "list_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional title for the list of accordions.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "accordions",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "expand_accordion",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="The accordion is collapsed by default. Select this option to have it expanded when the page loads.",
                                                        label="Expand accordion?",
                                                        required=False,
                                                    ),
                                                ),
                                                ("title", wagtail.blocks.CharBlock()),
                                                (
                                                    "body",
                                                    wagtail.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Add, remove, or reorder accordions.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "header",
                        wagtail.blocks.CharBlock(
                            template="meinberlin_cms/blocks/header.html"
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
