# Generated by Django 4.2.11 on 2025-01-23 09:36

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0048_remove_storefrontcollection_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("projects", 4),
                    ("call_to_action", 8),
                    ("image_call_to_action", 10),
                    ("columns_text", 14),
                    ("activities", 17),
                    ("accordion_list", 23),
                    ("infographic", 25),
                    ("map_teaser", 26),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "meinberlin_cms/blocks/richtext_block.html"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 80}),
                    2: (
                        "meinberlin.apps.cms.blocks.ProjectSelectionBlock",
                        (),
                        {"label": "Project"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"min_num": 3}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("projects", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 5), ("link", 6), ("link_text", 7)]],
                        {},
                    ),
                    9: ("wagtail.images.blocks.ImageBlock", [], {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 9),
                                ("title", 1),
                                ("body", 5),
                                ("link", 6),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (2, "Two columns"),
                                (3, "Three columns"),
                                (4, "Four columns"),
                            ]
                        },
                    ),
                    12: ("wagtail.blocks.RichTextBlock", (), {"label": "Column body"}),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 11), ("columns", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Count"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("count", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the list of accordions.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "The accordion is collapsed by default. Select this option to have it expanded when the page loads.",
                            "label": "Expand accordion?",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("expand_accordion", 19), ("title", 6), ("body", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"help_text": "Add, remove, or reorder accordions."},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("list_title", 18), ("accordions", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("text_left", 24), ("text_center", 24), ("text_right", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 9), ("body", 5)]],
                        {},
                    ),
                },
            ),
        ),
    ]
