# Generated by Django 4.2.16 on 2025-01-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0048_alter_homepage_body"),
        ("meinberlin_cms", "0049_customimage_description_alter_homepage_body"),
    ]

    operations = []
