# Generated by Django 4.2.16 on 2025-01-29 06:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0050_merge_20250129_0731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footermenuitem",
            name="page_link",
            field=wagtail.fields.StreamField(
                [("link", 2), ("external_link", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 0), ("link", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please enter a full url which starts with https://",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 0), ("link", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("projects", 4),
                    ("user_action_bar", 12),
                    ("image_call_to_action", 17),
                    ("columns_text", 21),
                    ("activities", 24),
                    ("accordion_list", 30),
                    ("infographic", 32),
                    ("map_teaser", 33),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "meinberlin_cms/blocks/richtext_block.html"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 80}),
                    2: (
                        "meinberlin.apps.cms.blocks.ProjectSelectionBlock",
                        (),
                        {"label": "Project"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"min_num": 3}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("projects", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Use '%username%' in the text to display the username",
                            "label": "Body",
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please enter a full url which starts with https://",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "light"),
                                ("fulltone", "fulltone"),
                                ("primary", "primary"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 7), ("style", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Buttons"}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"label": "Body"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body_logged_in", 5),
                                ("buttons_logged_in", 10),
                                ("body_anonymous", 11),
                                ("buttons_anonymous", 10),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageBlock", [], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: ("wagtail.blocks.CharBlock", (), {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 13),
                                ("title", 1),
                                ("body", 14),
                                ("link", 15),
                                ("link_text", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (2, "Two columns"),
                                (3, "Three columns"),
                                (4, "Four columns"),
                            ]
                        },
                    ),
                    19: ("wagtail.blocks.RichTextBlock", (), {"label": "Column body"}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 18), ("columns", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Count"},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 22), ("count", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the list of accordions.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "The accordion is collapsed by default. Select this option to have it expanded when the page loads.",
                            "label": "Expand accordion?",
                            "required": False,
                        },
                    ),
                    27: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("expand_accordion", 26), ("title", 15), ("body", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"help_text": "Add, remove, or reorder accordions."},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("list_title", 25), ("accordions", 29)]],
                        {},
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("text_left", 31), ("text_center", 31), ("text_right", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 13), ("body", 14)]],
                        {},
                    ),
                },
            ),
        ),
    ]
