# Generated by Django 4.2.16 on 2025-01-31 11:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0051_alter_footermenuitem_page_link_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("projects", 4),
                    ("user_action_bar", 12),
                    ("image_call_to_action", 17),
                    ("columns_text", 21),
                    ("activities", 24),
                    ("accordion_list", 30),
                    ("teaser", 36),
                    ("map_teaser", 37),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "meinberlin_cms/blocks/richtext_block.html"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 80}),
                    2: (
                        "meinberlin.apps.cms.blocks.ProjectSelectionBlock",
                        (),
                        {"label": "Project"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"min_num": 3}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("projects", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Use '%username%' in the text to display the username",
                            "label": "Body",
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please enter a full url which starts with https://",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "light"),
                                ("fulltone", "fulltone"),
                                ("primary", "primary"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 7), ("style", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Buttons"}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"label": "Body"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body_logged_in", 5),
                                ("buttons_logged_in", 10),
                                ("body_anonymous", 11),
                                ("buttons_anonymous", 10),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageBlock", [], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: ("wagtail.blocks.CharBlock", (), {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 13),
                                ("title", 1),
                                ("body", 14),
                                ("link", 15),
                                ("link_text", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (2, "Two columns"),
                                (3, "Three columns"),
                                (4, "Four columns"),
                            ]
                        },
                    ),
                    19: ("wagtail.blocks.RichTextBlock", (), {"label": "Column body"}),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 18), ("columns", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Count"},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 22), ("count", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the list of accordions.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "The accordion is collapsed by default. Select this option to have it expanded when the page loads.",
                            "label": "Expand accordion?",
                            "required": False,
                        },
                    ),
                    27: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("expand_accordion", 26), ("title", 15), ("body", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"help_text": "Add, remove, or reorder accordions."},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("list_title", 25), ("accordions", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "Should the image be on the left or on the right?",
                        },
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {"max_length": 70}),
                    33: ("wagtail.blocks.RichTextBlock", (), {"max_length": 250}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 7), ("style", 8)]],
                        {"form_classname": "w-field w-panel", "required": False},
                    ),
                    35: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"form_classname": "w-field w-panel"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("alignment", 31),
                                ("title", 32),
                                ("body", 33),
                                ("button", 34),
                                ("image", 35),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 13), ("body", 14)]],
                        {},
                    ),
                },
            ),
        ),
    ]
