# Generated by Django 4.2.16 on 2025-02-12 16:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0052_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("projects", 4),
                    ("user_action_bar", 12),
                    ("icon_list", 18),
                    ("columns_text", 22),
                    ("activities", 25),
                    ("accordion_list", 32),
                    ("teaser", 38),
                    ("info_bar", 41),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "meinberlin_cms/blocks/richtext_block.html"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 80}),
                    2: (
                        "meinberlin.apps.cms.blocks.ProjectSelectionBlock",
                        (),
                        {"label": "Project"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"min_num": 3}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("projects", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Use '%username%' in the text to display the username",
                            "label": "Body",
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please enter a full url which starts with https://",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "light"),
                                ("fulltone", "fulltone"),
                                ("primary", "primary"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 7), ("style", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Buttons"}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"label": "Body"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body_logged_in", 5),
                                ("buttons_logged_in", 10),
                                ("body_anonymous", 11),
                                ("buttons_anonymous", 10),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the list of panels.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.images.blocks.ImageBlock", [], {}),
                    15: ("wagtail.blocks.RichTextBlock", (), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 14), ("body", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("icon_list_blocks", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (2, "Two columns"),
                                (3, "Three columns"),
                                (4, "Four columns"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.RichTextBlock", (), {"label": "Column body"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 19), ("columns", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Count"},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("count", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the list of accordions.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "The accordion is collapsed by default. Select this option to have it expanded when the page loads.",
                            "label": "Expand accordion?",
                            "required": False,
                        },
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {}),
                    29: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("expand_accordion", 27), ("title", 28), ("body", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (30,),
                        {"help_text": "Add, remove, or reorder accordions."},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("list_title", 26), ("accordions", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "Should the image be on the left or on the right?",
                        },
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"max_length": 70}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"max_length": 250}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 7), ("style", 8)]],
                        {"form_classname": "w-field w-panel", "required": False},
                    ),
                    37: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"form_classname": "w-field w-panel"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("alignment", 33),
                                ("title", 34),
                                ("body", 35),
                                ("button", 36),
                                ("image", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 6), ("link", 39)]],
                        {"form_classname": "w-field w-panel", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 15), ("image", 37), ("link", 40)]],
                        {},
                    ),
                },
            ),
        ),
    ]
